Post.create(title: 'How to create rails apps', author: 'Michaelo Angelo', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer urna ante, venenatis a dictum ut, dapibus et dui. Donec pellentesque maximus lacus, sit amet fringilla elit. Suspendisse accumsan turpis augue, id malesuada lacus eleifend id. Vestibulum aliquet tellus nec quam ultrices suscipit. Donec vehicula, felis eu rutrum eleifend, lacus ante commodo elit, nec lacinia mi dolor ut ante. Sed eget libero at odio accumsan convallis in at ante. Aliquam erat volutpat. Proin erat diam, hendrerit ac sagittis nec, lobortis sed mauris. Nulla porttitor placerat risus, venenatis ultrices mauris aliquet vitae. Suspendisse ut elit mi. Nullam nunc ex, cursus in erat vitae, pulvinar dictum lectus.

Nunc malesuada quis ligula dictum feugiat. Vestibulum vel luctus odio. Nullam posuere ultrices justo, ut euismod justo mattis vel. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras rutrum erat id est sagittis blandit. In ac justo at ipsum convallis eleifend at in ante. In ut vulputate mauris, non ullamcorper tellus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In et leo leo.

Etiam scelerisque quis mi id dictum. Praesent viverra consequat sem posuere mollis. Proin dictum eu turpis sed porta. Maecenas auctor, augue a consequat imperdiet, lectus quam molestie dui, at blandit tortor risus blandit dui. Ut facilisis enim vitae diam porttitor, quis blandit lacus eleifend. Praesent tincidunt sapien venenatis imperdiet tempor. Aliquam in dapibus tellus. Donec dapibus hendrerit vestibulum. Praesent lobortis nulla sit amet mauris efficitur luctus. Nulla porta arcu eros, ac placerat eros rutrum vel. Donec pulvinar arcu orci, et luctus nisi lobortis eu. Praesent porta, justo sed ultrices ullamcorper, risus nisl laoreet diam, id mattis orci nunc nec lacus. Fusce nulla purus, lacinia et elementum id, placerat ut ipsum. Mauris ultrices rhoncus lorem sit amet imperdiet.

Duis pulvinar rhoncus placerat. Sed tincidunt porttitor ligula vulputate vulputate. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc ultrices ante ut tristique cursus. Donec finibus magna at purus fermentum, in ornare enim accumsan. Suspendisse potenti. Suspendisse potenti. Nullam aliquet justo eu velit condimentum facilisis. Praesent quam felis, facilisis ut rhoncus non, porttitor sit amet augue. Proin ut nibh eu leo suscipit lobortis eu vulputate orci. Mauris et tincidunt orci. Nam vestibulum purus metus, eget dignissim leo mattis sit amet. Suspendisse nec nisl ornare, pellentesque velit et, sagittis dolor. Proin vulputate rhoncus ante sed sagittis.

Praesent feugiat euismod elit, quis sollicitudin lectus luctus eget. Integer nulla lacus, viverra sed consequat in, fermentum vitae sapien. Donec nec nisi dictum, luctus est a, aliquam nisi. Integer quis massa ac lorem rhoncus dictum. Sed iaculis leo quis est egestas maximus. Aenean imperdiet, ante in interdum pulvinar, tortor neque tempor nisi, vitae congue ipsum erat sed nulla. Duis ut erat eu magna gravida efficitur aliquet in dolor. Proin dapibus eget enim sit amet ullamcorper. Proin at est consectetur, vehicula elit vehicula, rhoncus mi. Donec facilisis magna a lacus euismod, sed luctus dui luctus. Quisque laoreet, urna quis lobortis venenatis, neque metus viverra lectus, in euismod lorem odio iaculis ligula. Cras viverra dolor id nulla posuere, vel convallis massa aliquet. Fusce ligula est, aliquam non egestas ut, feugiat quis leo. Aliquam posuere lobortis vestibulum. Nam volutpat fringilla mauris eget vestibulum. Praesent dictum tempor enim eu sodales.')
Post.create(title: 'JavaScript basics', author: 'Zbigniew', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ut nunc sit amet sem tempor egestas. Cras ut leo ac tellus scelerisque sagittis at at mi. In at nisi a enim fermentum finibus. Morbi varius nisl lorem, ut pretium sem maximus at. Aenean sed maximus quam. Maecenas vel tortor id nisi egestas egestas. Morbi efficitur, ipsum eget viverra lobortis, nisi nisi sagittis lacus, eu congue nisi felis vitae justo. Mauris vel eleifend ligula. Morbi a nibh tristique, laoreet urna sit amet, dignissim turpis. Vestibulum sagittis sapien non congue ornare. Etiam fermentum augue egestas lacus faucibus, non venenatis velit ultrices. Curabitur vitae est in nunc accumsan rutrum. Cras sollicitudin, massa eu molestie facilisis, erat nulla iaculis metus, et dignissim quam nunc at enim. Pellentesque at efficitur ipsum.

Vestibulum lectus lectus, sollicitudin eu dictum et, ultricies sed elit. Nullam iaculis orci vitae nulla dapibus sodales. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean sit amet ante ut nunc euismod molestie ut sed mauris. Donec porta vel dolor quis tempor. Nulla semper sapien at justo luctus, at consequat metus pharetra. Nulla volutpat, est eu blandit posuere, metus eros efficitur turpis, vel facilisis neque nunc consectetur mauris. In interdum, nibh sit amet consequat rutrum, nulla ligula tincidunt tellus, non condimentum tortor sapien eget lacus.

Cras nec sodales turpis. Curabitur sagittis enim quis tortor viverra commodo. Sed in massa ligula. Nam egestas imperdiet gravida. Nullam commodo magna pulvinar massa consectetur lobortis. Phasellus non finibus tellus. Nulla facilisi. Nunc vel commodo sapien. Morbi ac mi sed leo tincidunt pellentesque eget ac quam.

Vestibulum posuere pharetra pretium. Vivamus luctus porta purus hendrerit varius. Nulla tempus nec nisl vel venenatis. Nulla quis justo sed neque consectetur lobortis euismod vitae sapien. Integer eget aliquet sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse potenti. Vivamus at nunc in erat vehicula vestibulum id sed lorem. Mauris finibus mauris eu ex faucibus, et egestas odio maximus. Nunc pulvinar vehicula augue, quis ullamcorper sem aliquet eget. Mauris ultricies purus at felis accumsan, efficitur maximus dolor cursus. Nulla consectetur imperdiet augue, eu aliquam leo eleifend aliquam. Praesent tortor nibh, vehicula id quam vitae, convallis lobortis ex.

Etiam iaculis elit et commodo eleifend. Integer tellus purus, dignissim vitae tortor eu, interdum elementum nibh. Nulla facilisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin eu est est. Donec interdum consectetur erat, ut porttitor metus molestie nec. Etiam sollicitudin erat nec massa volutpat tincidunt vel a ipsum. Fusce in sagittis justo.')
Post.create(title: 'Ruby basics', author: 'Zbigniew', content: 'Phasellus bibendum lacinia nulla, eget euismod nunc semper vel. Vestibulum nec tortor sed nunc semper dictum. Aenean pretium a ligula at condimentum. Ut eu fermentum massa, ut luctus augue. Suspendisse at bibendum nulla. In quis condimentum erat. Suspendisse lobortis molestie ex, in rhoncus leo pretium ut. Ut erat lorem, efficitur in metus quis, tempus vestibulum erat. Pellentesque lorem diam, ultricies vel lorem eu, elementum bibendum purus. Quisque eget porta ligula. Nunc ultrices, magna et laoreet ornare, ipsum orci ultricies elit, vel ultricies lectus enim a diam. Phasellus nec ipsum ante. Maecenas maximus lacinia sapien quis fermentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ipsum massa, sagittis consectetur ligula quis, accumsan porttitor tortor. Vivamus a faucibus eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ut nunc sit amet sem tempor egestas. Cras ut leo ac tellus scelerisque sagittis at at mi. In at nisi a enim fermentum finibus. Morbi varius nisl lorem, ut pretium sem maximus at. Aenean sed maximus quam. Maecenas vel tortor id nisi egestas egestas. Morbi efficitur, ipsum eget viverra lobortis, nisi nisi sagittis lacus, eu congue nisi felis vitae justo. Mauris vel eleifend ligula. Morbi a nibh tristique, laoreet urna sit amet, dignissim turpis. Vestibulum sagittis sapien non congue ornare. Etiam fermentum augue egestas lacus faucibus, non venenatis velit ultrices. Curabitur vitae est in nunc accumsan rutrum. Cras sollicitudin, massa eu molestie facilisis, erat nulla iaculis metus, et dignissim quam nunc at enim. Pellentesque at efficitur ipsum.

Vestibulum lectus lectus, sollicitudin eu dictum et, ultricies sed elit. Nullam iaculis orci vitae nulla dapibus sodales. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean sit amet ante ut nunc euismod molestie ut sed mauris. Donec porta vel dolor quis tempor. Nulla semper sapien at justo luctus, at consequat metus pharetra. Nulla volutpat, est eu blandit posuere, metus eros efficitur turpis, vel facilisis neque nunc consectetur mauris. In interdum, nibh sit amet consequat rutrum, nulla ligula tincidunt tellus, non condimentum tortor sapien eget lacus.

Cras nec sodales turpis. Curabitur sagittis enim quis tortor viverra commodo. Sed in massa ligula. Nam egestas imperdiet gravida. Nullam commodo magna pulvinar massa consectetur lobortis. Phasellus non finibus tellus. Nulla facilisi. Nunc vel commodo sapien. Morbi ac mi sed leo tincidunt pellentesque eget ac quam.

Vestibulum posuere pharetra pretium. Vivamus luctus porta purus hendrerit varius. Nulla tempus nec nisl vel venenatis. Nulla quis justo sed neque consectetur lobortis euismod vitae sapien. Integer eget aliquet sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse potenti. Vivamus at nunc in erat vehicula vestibulum id sed lorem. Mauris finibus mauris eu ex faucibus, et egestas odio maximus. Nunc pulvinar vehicula augue, quis ullamcorper sem aliquet eget. Mauris ultricies purus at felis accumsan, efficitur maximus dolor cursus. Nulla consectetur imperdiet augue, eu aliquam leo eleifend aliquam. Praesent tortor nibh, vehicula id quam vitae, convallis lobortis ex.

Etiam iaculis elit et commodo eleifend. Integer tellus purus, dignissim vitae tortor eu, interdum elementum nibh. Nulla facilisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin eu est est. Donec interdum consectetur erat, ut porttitor metus molestie nec. Etiam sollicitudin erat nec massa volutpat tincidunt vel a ipsum. Fusce in sagittis justo.')
